from __future__ import annotations

import difflib
import json
from pathlib import Path

from ai_vuln_analyzer.core.schemas import PatchSuggestion, VulnerabilityFinding
from ai_vuln_analyzer.llm.base import LLMClient
from ai_vuln_analyzer.llm.prompts import student_prompt


class Student:
    def __init__(self, llm: LLMClient) -> None:
        self.llm = llm

    def generate_patches(self, findings: list[VulnerabilityFinding]) -> list[PatchSuggestion]:
        return [self._generate_patch(finding) for finding in findings]

    def _generate_patch(self, finding: VulnerabilityFinding) -> PatchSuggestion:
        path = Path(finding.location.file)
        lines = path.read_text(encoding="utf-8").splitlines()
        start = max((finding.location.line_start or 1) - 1, 0)
        end = finding.location.line_end or start + 1
        original = "\n".join(lines[start:end])
        patched = self._patch_text(original, finding)
        system_prompt, user_prompt = student_prompt(finding.model_dump_json())
        raw = self.llm.complete(system_prompt, user_prompt)
        llm_confidence = 0.75
        explanation = "Guarded patch suggestion generated by heuristic student."
        try:
            data = json.loads(raw)
            llm_confidence = float(data.get("confidence", llm_confidence))
            explanation = data.get("explanation", explanation)
        except json.JSONDecodeError:
            pass
        diff = "\n".join(
            difflib.unified_diff(
                original.splitlines(),
                patched.splitlines(),
                fromfile="original",
                tofile="patched",
                lineterm="",
            )
        )
        return PatchSuggestion(
            finding_id=finding.id,
            explanation=explanation,
            original_code=original,
            patched_code=patched,
            diff=diff,
            confidence=llm_confidence,
        )

    def _patch_text(self, original: str, finding: VulnerabilityFinding) -> str:
        sink = finding.sink or ""
        if sink == "strcpy":
            target = "buf"
            if "strcpy(" in original:
                try:
                    args = original.split("strcpy(", 1)[1].split(")", 1)[0]
                    target = args.split(",")[0].strip()
                except IndexError:
                    target = "buf"
            return (
                "if (input != NULL) {\n"
                f"    strncpy({target}, input, sizeof({target}) - 1);\n"
                f"    {target}[sizeof({target}) - 1] = '\\0';\n"
                "}"
            )
        if sink == "memcpy":
            return (
                "if (count <= SIZE_MAX / sizeof(int)) {\n"
                "    memcpy(buf, src, count * sizeof(int));\n"
                "}"
            )
        if finding.cwe == "CWE-476":
            first_line = original.splitlines()[0] if original.splitlines() else "char *p = malloc(64);"
            return f"{first_line}\nif (p == NULL) {{ return; }}\nstrcpy(p, input);"
        if finding.cwe == "CWE-416":
            return "free(p);\np = NULL;\nif (p != NULL) {\n    printf(\"%s\\n\", p);\n}"
        return f"/* review required */\n{original}"
